# Generated by Django 2.0.2 on 2018-04-08 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180408_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
