# Generated by Django 2.0.3 on 2018-07-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(choices=[('PD', 'Primary Design'), ('CD', 'Civil Design'), ('SD', 'Secondary Design'), ('OD', 'Overhead Design'), ('UD', 'Underground Design')], max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='dashboard.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('name', 'project')},
        ),
    ]
